version: "2"

services:
  database:
    image: postgres:15
    restart: unless-stopped
    container_name: backend_postgres
    volumes:
      - ~/.pg/pg_data/backend:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "127.0.0.1:5432:5432"
  backend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    image: backend_django:latest
    container_name: backend_django
    # ports:
    #   - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./static:/ParkingBackend/static:consistent
      - ./media:/ParkingBackend/media:consistent
      - ./ParkingBackend/settings.py:/ParkingBackend/ParkingBackend/settings.py:consistent
    env_file:
      - .env.docker
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 ParkingBackend.wsgi:application"
  nginx:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: backend_nginx
    image: backend_nginx
    volumes:
      - ./static:/ParkingBackend/static:consistent
      - ./media:/ParkingBackend/media:consistent
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"

volumes:
  certs:
  vhost:
  html:
