# Generated by Django 4.2.7 on 2023-11-25 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_purpose', models.CharField(choices=[('line', 'Line'), ('polygon', 'Polygon')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('line_string', 'Line String'), ('polygon', 'Polygon')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('aggregating', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car')], default='car', max_length=30)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicapped', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mock',
        ),
    ]
