# Generated by Django 4.2.7 on 2023-11-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_purpose', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('line_string', 'Line String'), ('polygon', 'Polygon')], max_length=30)),
                ('coordinates', models.ManyToManyField(related_name='locations', to='api.coordinate')),
            ],
            options={
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('aggregating', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.location')),
            ],
            options={
                'verbose_name_plural': 'Парковки',
            },
        ),
        migrations.CreateModel(
            name='Parkomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='point', on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
            ],
            options={
                'verbose_name_plural': 'Паркоматы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car')], default='car', max_length=30)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicapped', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Парковочные места',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='point', on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
            ],
            options={
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.DeleteModel(
            name='Mock',
        ),
        migrations.AddField(
            model_name='parking',
            name='prices',
            field=models.ManyToManyField(related_name='parkings', to='api.price'),
        ),
        migrations.AddField(
            model_name='parking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.space'),
        ),
    ]
