# Generated by Django 4.2.7 on 2023-11-25 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='parking',
            name='price_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='space_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.space'),
            preserve_default=False,
        ),
    ]
