# Generated by Django 4.2.7 on 2023-11-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_coordinate_location_parking_parkomat_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('credentials', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
            options={
                'verbose_name_plural': 'Брони',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeed', 'Succeed')], default='pending', max_length=30)),
                ('payment_id', models.CharField(db_index=True, max_length=50)),
                ('duration', models.DurationField()),
                ('secret_key', models.CharField(max_length=50)),
                ('credentials', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
        ),
    ]
