# Generated by Django 4.2.7 on 2023-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_empty', models.BooleanField(default=False)),
                ('reservation_start_time', models.DateTimeField(null=True)),
                ('reservation_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Оплаты'},
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_spots',
            field=models.ManyToManyField(blank=True, related_name='parking', to='api.parkingspot'),
        ),
    ]
