# Generated by Django 4.2.7 on 2023-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parkingspot_alter_payment_options_delete_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='empty',
            field=models.IntegerField(null=True),
        ),
    ]
