# Generated by Django 4.2.7 on 2023-11-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adadd_location_id_to_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcoordinate',
            old_name='coordinate_id',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='locationcoordinate',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='center_id',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='price_id',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='space_id',
            new_name='space',
        ),
    ]
