# Generated by Django 4.2.7 on 2023-11-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_space_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='empty',
        ),
    ]
