# Generated by Django 4.2.7 on 2023-11-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_e_id_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='price',
        ),
        migrations.AlterField(
            model_name='locationcoordinate',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinate'),
        ),
        migrations.AlterField(
            model_name='locationcoordinate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.CreateModel(
            name='PriceParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.price')),
            ],
        ),
    ]
