# Generated by Django 4.2.7 on 2023-11-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_price_parking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='locationcoordinate',
            options={'verbose_name_plural': 'Локация-Координаты'},
        ),
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name_plural': 'Парковки'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='priceparking',
            options={'verbose_name_plural': 'Цены парковок'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name_plural': 'Парковочные места'},
        ),
        migrations.AlterField(
            model_name='category',
            name='zone_purpose',
            field=models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], max_length=30),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='point', on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
            ],
            options={
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.CreateModel(
            name='Parkomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='point', on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coordinate')),
            ],
            options={
                'verbose_name_plural': 'Паркоматы',
            },
        ),
    ]
