# Generated by Django 4.2.7 on 2023-11-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_parking_parking_spots_parkingspot_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='space',
        ),
        migrations.AddField(
            model_name='parking',
            name='empty_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='handicapped_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='total_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.parking'),
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
