# Generated by Django 4.2.7 on 2023-11-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_parking_space_parking_empty_spots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
        ),
    ]
