# Generated by Django 4.2.7 on 2023-11-25 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(max_length=50)),
                ('booking_start_time', models.DateTimeField(auto_now_add=True)),
                ('booking_end_time', models.DateTimeField()),
                ('total_price', models.IntegerField(null=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspot')),
            ],
            options={
                'verbose_name_plural': 'Брони',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=50)),
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credentials', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[('pending', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат средств')], default='pending', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking')),
            ],
            options={
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
