# Generated by Django 4.2.7 on 2023-11-26 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_booking_transaction_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_end_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='credentials',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
