# Generated by Django 4.2.7 on 2023-11-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_booking_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fio',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
