# Generated by Django 4.2.7 on 2023-11-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_comment_fio_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
