# Generated by Django 4.2.7 on 2023-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_url',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
